<div id="pg" class="container-fluid">
	<div class="row blue_bg" style="background-image:url('/img/principals.svg');">
    	<div></div>
    </div>
	<div class="row">
	    <div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1">
        	<h1>Teresa Nelson, Ph.D.</h1>
            <p>Teresa Nelson was born in Minneapolis, lived in Europe and then found her way to Boston, a city that she says, “is poised to become one of the great world cities of the century.” With an MBA and PhD, she has a strategic perspective that emphasizes organizational value creation defined around the outcomes of wealth, jobs, innovation and social welfare. Her work on the governance of high growth firms, including team management and product development, focuses on the negotiating relationship of investors, founders and top team members providing human, financial and social capital to achieve mutual interests: the success of the firm. Her research and teaching on innovation as practice and process explores creativity, funding and diversity mostly around the industries of tech, energy and life sciences. She says, “We’re only at the beginning of the journey of realizing value from diversity of teams – the benefits are potentially tremendous and the challenges of realizing that value by managers is substantial. The link of creativity and diversity is only one aspect of the equation – real cultural competence takes commitment on many levels.”</p>
            <p>Nelson was appointed in 2013 to a three year term as a member of the National Women’s Business Council, a 15 member board advising the White House, Congress and the Small Business Administration on issues of women and business. She also serves as a Global Advisory Board member for Astia and as a Scientific Advisory Board member for Women Equity Growth, an arm of Bryan-Garnier, Europe’s leading private equity firm in the entrepreneurial space. One of the projects she finds, “most interesting” of late is an effort to understand and evaluate the flow of over $4B per year from the US federal government to tech innovators through the national Small Business Innovation Research (SBIR) grants program. “This public commitment to innovation is shaping our technology future.” Nelson holds the position of Professor of strategic management and entrepreneurship at Simmons College in Boston and also serves as a visiting faculty member to the PhD program at the University of Liège in Belgium.</p>
            <p><a href="https://www.linkedin.com/in/drteresanelson" target="_blank">Connect with Teresa on Linkedin</a> | <a href="/file/Nelson-Research-Summary-July-2016.pdf" target="_blank">Read Teresa's Research Summary</a></p>
        </div>
    </div>
</div>